name: Build nightly

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  set-owner-lc:
    runs-on: ubuntu-24.04
    outputs:
      OWNER_LC: ${{ steps.set-owner-lc.outputs.OWNER_OUTPUT }}
    steps:
      - name: Set lowercase owner name
        id: set-owner-lc
        run: |
          OWNER_LC="${OWNER,,}"  
          echo "OWNER_OUTPUT=${OWNER_LC}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}

  build-docker:
    if: github.ref_name == 'dev'
    name: Docker
    needs: set-owner-lc
    uses: ./.github/workflows/build-docker-image.yml
    with:
      OWNER_LC: ${{ needs.set-owner-lc.outputs.OWNER_LC }}

  build-devices:
    if: github.ref_name == 'dev'
    name: Build Devices
    needs:
      - set-owner-lc
      - build-docker
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: RK3326
            project: Rockchip
          - device: RK3399
            project: Rockchip
          - device: RK3566
            project: Rockchip
          - device: RK3588
            project: Rockchip
          - device: S922X
            project: Amlogic
          - device: H700
            project: Allwinner
          - device: SM8250
            project: Qualcomm
          - device: SM8550
            project: Qualcomm
    uses: ./.github/workflows/build-device.yml
    secrets: inherit
    with:
      PROJECT: ${{ matrix.project }}
      DEVICE: ${{ matrix.device }}
      OWNER_LC: ${{ needs.set-owner-lc.outputs.OWNER_LC }}

  rerun-failed-jobs:
    if: failure() && fromJSON(github.run_attempt) < 3 && github.ref_name == 'dev'
    needs: build-devices
    runs-on: ubuntu-24.04
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run retry-workflow.yml -F run_id=${{ github.run_id }}
